services:

  store_database:
    image: postgres:latest
    container_name: store_db
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=store_db
    ports:
      - 5432:5432
    restart: always

  redis_cache:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    restart: always
 
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    command: "start-dev"
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_db:5433/keycloak
      - KC_DB_USERNAME=kc_admin
      - KC_DB_PASSWORD=kc_password
    depends_on:
      - keycloak_db
    restart: always
    
  keycloak_db:
    image: postgres:latest
    container_name: keycloak_db
    environment:
      - POSTGRES_USER=kc_admin
      - POSTGRES_PASSWORD=kc_password
      - POSTGRES_DB=keycloak
    ports:
      - 5433:5433
    restart: always

  store.api:
    image: ${DOCKER_REGISTRY-}storeapi
    build:
      context: .
      dockerfile: src/Store.API/Dockerfile
    depends_on:
        - store_database
        - redis_cache
        - keycloak
    environment:
        - ConnectionStrings:DefaultConnection="Host=store_database;Database=store_db;Username=username;Password=password;"
        - ASPNETCORE_URLS=http://+80;