name: vault

services:
  haproxy:
    image: haproxy:2.8.15
    ports:
      - "443:443"
    volumes:
    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    - ${CERTIFICATES}/haproxy:/usr/local/etc/haproxy
    networks:
    - vault_net
    
  ha_storage:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    networks:
    - vault_net

  vault-node1:
    image: hashicorp/vault
    volumes:
      - ./vault/config/node_1.hcl:/vault/config/node_1.hcl
      - ./vault/data:/vault/data
      - ${CERTIFICATES}/vault:/vault/certificates
    cap_add:
      - IPC_LOCK
    depends_on:
      - ha_storage
    command: "vault server -config=/vault/config/node_1.hcl"
    networks:
      vault_net:
        ipv4_address: 10.0.0.11

  vault-node2:
    image: hashicorp/vault
    volumes:
      - ./vault/config/node_2.hcl:/vault/config/node_2.hcl
      - ./vault/data:/vault/data
      - ${CERTIFICATES}/vault:/vault/certificates
    cap_add:
      - IPC_LOCK
    depends_on:
      - ha_storage
    command: "vault server -config=/vault/config/node_2.hcl"
    networks:
      vault_net:
        ipv4_address: 10.0.0.12

  vault-node3:
    image: hashicorp/vault
    volumes:
      - ./vault/config/node_3.hcl:/vault/config/node_3.hcl
      - ./vault/data:/vault/data
      - ${CERTIFICATES}/vault:/vault/certificates
    cap_add:
      - IPC_LOCK
    depends_on:
      - ha_storage
    command: "vault server -config=/vault/config/node_3.hcl"
    networks:
      vault_net:
        ipv4_address: 10.0.0.13
    
networks:
  vault_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24