name: vault

services:
  vault:
    image: hashicorp/vault
    volumes:
      - ./vault/config/vault.hcl:/vault/config/vault.hcl
      - ./vault/data:/vault/data
      - ${VAULT_CERT}:/vault/certificates/vault.crt
      - ${VAULT_KEY}:/vault/certificates/vault.key
    ports: 
      - "8200:8200"
    depends_on:
      - ha_storage
    command: "vault server -config=/vault/config/vault.hcl"
    extra_hosts:
      - "vault.localhost:127.0.0.1"
  
  ha_storage:
    image: hashicorp/consul
    ports:
      - "8500:8500"
